"""Global configuration for FX AgentTeam."""

FX_PAIRS = ["EURUSD=X", "GBPUSD=X", "USDJPY=X", "AUDUSD=X"]
DEFAULT_PAIR = "EURUSD=X"
DATA_START = "2018-01-01"
DATA_END = "2025-12-31"
TIMEFRAME = "1d"
INITIAL_CAPITAL = 100_000
MAX_ITERATIONS = 30
TARGET_SHARPE = 1.5
TARGET_GRADE = "B"
OUTPUT_DIR = "output"
LOG_LEVEL = "INFO"

# Risk constraints
MIN_STOP_LOSS = 0.005
MAX_STOP_LOSS = 0.05
MIN_POSITION_PCT = 0.01
MAX_POSITION_PCT = 0.20
MIN_MAX_DRAWDOWN = 0.05
MAX_MAX_DRAWDOWN = 0.25
MIN_REWARD_RISK_RATIO = 1.5
