//+------------------------------------------------------------------+
//|                                        AgentTeam_StochRSI.mq5    |
//|                        Generated by FX AgentTeam Optimizer       |
//|                        Strategy: strat_e4c42302 v2               |
//|                        Stochastic(16,4) + RSI(15)                |
//+------------------------------------------------------------------+
#property copyright "FX AgentTeam"
#property version   "2.00"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\AccountInfo.mqh>
#include <Trade\SymbolInfo.mqh>

//+------------------------------------------------------------------+
//| Input Parameters                                                  |
//+------------------------------------------------------------------+
input group "=== Indicator Settings ==="
input int      InpStochKPeriod    = 16;       // Stochastic %K Period
input int      InpStochDPeriod    = 4;        // Stochastic %D (Smoothing)
input int      InpStochSlowing    = 3;        // Stochastic Slowing
input int      InpRSIPeriod       = 15;       // RSI Period

input group "=== Entry Conditions ==="
input double   InpStochEntryLevel = 20.0;     // Stochastic Entry (below)
input double   InpRSIEntryLevel   = 35.0;     // RSI Entry (below)

input group "=== Exit Conditions ==="
input double   InpStochExitLevel  = 80.0;     // Stochastic Exit (above)

input group "=== Risk Management ==="
input double   InpStopLossPct     = 3.2;      // Stop Loss (%)
input double   InpTakeProfitPct   = 5.9;      // Take Profit (%)
input double   InpRiskPerTrade    = 8.0;      // Max Position Size (% of Balance)
input double   InpMaxDrawdownPct  = 16.0;     // Max Drawdown (%) - stops trading
input double   InpFixedLot        = 0.0;      // Fixed Lot (0 = auto sizing)

input group "=== General ==="
input int      InpMagicNumber     = 20260309; // Magic Number
input int      InpMaxSlippage     = 30;       // Max Slippage (points)
input ENUM_TIMEFRAMES InpTimeframe = PERIOD_D1; // Timeframe
input bool     InpTradeOnlyOnNewBar = true;   // Trade only on new bar

//+------------------------------------------------------------------+
//| Global Variables                                                  |
//+------------------------------------------------------------------+
CTrade         trade;
CPositionInfo  posInfo;
CAccountInfo   accInfo;
CSymbolInfo    symInfo;

int            handleStoch;
int            handleRSI;

double         stochMain[];
double         stochSignal[];
double         rsiBuffer[];

datetime       lastBarTime;
double         initialBalance;
bool           drawdownHalt;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
{
   // Validate inputs
   if(InpStochKPeriod < 1 || InpStochDPeriod < 1 || InpRSIPeriod < 1)
   {
      Print("ERROR: Invalid indicator periods");
      return INIT_PARAMETERS_INCORRECT;
   }

   // Setup trade object
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpMaxSlippage);
   trade.SetTypeFilling(ORDER_FILLING_FOK);
   trade.SetMarginMode();

   // Symbol info
   symInfo.Name(_Symbol);
   symInfo.Refresh();

   // Create indicator handles
   handleStoch = iStochastic(_Symbol, InpTimeframe, InpStochKPeriod, InpStochDPeriod, InpStochSlowing, MODE_SMA, STO_LOWHIGH);
   handleRSI   = iRSI(_Symbol, InpTimeframe, InpRSIPeriod, PRICE_CLOSE);

   if(handleStoch == INVALID_HANDLE || handleRSI == INVALID_HANDLE)
   {
      Print("ERROR: Failed to create indicator handles");
      return INIT_FAILED;
   }

   // Set buffers as series
   ArraySetAsSeries(stochMain, true);
   ArraySetAsSeries(stochSignal, true);
   ArraySetAsSeries(rsiBuffer, true);

   // Initialize state
   lastBarTime    = 0;
   initialBalance = accInfo.Balance();
   drawdownHalt   = false;

   Print("=== AgentTeam EA Initialized ===");
   Print("Strategy: Stochastic(", InpStochKPeriod, ",", InpStochDPeriod, ") + RSI(", InpRSIPeriod, ")");
   Print("Entry: Stoch < ", InpStochEntryLevel, " AND RSI < ", InpRSIEntryLevel);
   Print("Exit:  Stoch > ", InpStochExitLevel);
   Print("SL: ", InpStopLossPct, "% | TP: ", InpTakeProfitPct, "%");
   Print("================================");

   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   if(handleStoch != INVALID_HANDLE) IndicatorRelease(handleStoch);
   if(handleRSI   != INVALID_HANDLE) IndicatorRelease(handleRSI);

   Print("AgentTeam EA removed. Reason: ", reason);
}

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
{
   // New bar check
   if(InpTradeOnNewBar && !IsNewBar())
      return;

   // Refresh symbol data
   symInfo.Refresh();
   symInfo.RefreshRates();

   // Drawdown protection
   if(CheckDrawdownHalt())
      return;

   // Copy indicator values
   if(!RefreshIndicators())
      return;

   // Get current indicator values (index 1 = completed bar)
   double stochValue = stochMain[1];
   double rsiValue   = rsiBuffer[1];

   // Display on chart
   Comment(StringFormat(
      "AgentTeam EA | %s %s\n"
      "Stochastic: %.2f (Entry<%.0f | Exit>%.0f)\n"
      "RSI: %.2f (Entry<%.0f)\n"
      "Position: %s | DD: %.2f%%",
      _Symbol, EnumToString(InpTimeframe),
      stochValue, InpStochEntryLevel, InpStochExitLevel,
      rsiValue, InpRSIEntryLevel,
      HasPosition() ? "LONG" : "NONE",
      GetCurrentDrawdown()
   ));

   // --- Trading Logic ---
   if(HasPosition())
   {
      // Check exit signal: Stochastic > exit level
      if(stochValue > InpStochExitLevel)
      {
         ClosePosition("Signal Exit: Stoch=" + DoubleToString(stochValue, 2));
      }
   }
   else
   {
      // Check entry signal: Stochastic < entry level AND RSI < entry level
      if(stochValue < InpStochEntryLevel && rsiValue < InpRSIEntryLevel)
      {
         OpenBuyPosition(stochValue, rsiValue);
      }
   }
}

//+------------------------------------------------------------------+
//| Check if a new bar has formed                                     |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime currentBarTime = iTime(_Symbol, InpTimeframe, 0);
   if(currentBarTime == lastBarTime)
      return false;
   lastBarTime = currentBarTime;
   return true;
}

//+------------------------------------------------------------------+
//| Refresh indicator buffers                                         |
//+------------------------------------------------------------------+
bool RefreshIndicators()
{
   if(CopyBuffer(handleStoch, MAIN_LINE, 0, 3, stochMain) < 3)
   {
      Print("WARNING: Failed to copy Stochastic main buffer");
      return false;
   }
   if(CopyBuffer(handleStoch, SIGNAL_LINE, 0, 3, stochSignal) < 3)
   {
      Print("WARNING: Failed to copy Stochastic signal buffer");
      return false;
   }
   if(CopyBuffer(handleRSI, 0, 0, 3, rsiBuffer) < 3)
   {
      Print("WARNING: Failed to copy RSI buffer");
      return false;
   }
   return true;
}

//+------------------------------------------------------------------+
//| Check if we have an open position for this EA                     |
//+------------------------------------------------------------------+
bool HasPosition()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(posInfo.SelectByIndex(i))
      {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber)
            return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Calculate lot size based on risk                                  |
//+------------------------------------------------------------------+
double CalculateLotSize(double slPoints)
{
   if(InpFixedLot > 0)
      return NormalizeLot(InpFixedLot);

   double balance     = accInfo.Balance();
   double riskAmount  = balance * InpRiskPerTrade / 100.0;
   double tickValue   = symInfo.TickValue();
   double tickSize    = symInfo.TickSize();

   if(tickValue == 0 || tickSize == 0 || slPoints == 0)
      return NormalizeLot(symInfo.LotsMin());

   double lotSize = riskAmount / (slPoints / tickSize * tickValue);
   return NormalizeLot(lotSize);
}

//+------------------------------------------------------------------+
//| Normalize lot size to broker constraints                          |
//+------------------------------------------------------------------+
double NormalizeLot(double lots)
{
   double minLot  = symInfo.LotsMin();
   double maxLot  = symInfo.LotsMax();
   double lotStep = symInfo.LotsStep();

   lots = MathMax(minLot, lots);
   lots = MathMin(maxLot, lots);
   lots = MathFloor(lots / lotStep) * lotStep;
   return NormalizeDouble(lots, 2);
}

//+------------------------------------------------------------------+
//| Open a buy position                                               |
//+------------------------------------------------------------------+
void OpenBuyPosition(double stochVal, double rsiVal)
{
   double ask = symInfo.Ask();

   if(ask == 0)
   {
      Print("ERROR: Ask price is 0");
      return;
   }

   // Calculate SL and TP from percentage
   double slPrice = NormalizeDouble(ask * (1.0 - InpStopLossPct / 100.0), symInfo.Digits());
   double tpPrice = NormalizeDouble(ask * (1.0 + InpTakeProfitPct / 100.0), symInfo.Digits());
   double slPoints = ask - slPrice;

   // Calculate lot size
   double lots = CalculateLotSize(slPoints);

   // Validate SL/TP distances
   double minStopLevel = symInfo.StopsLevel() * symInfo.Point();
   if(ask - slPrice < minStopLevel)
   {
      slPrice = NormalizeDouble(ask - minStopLevel, symInfo.Digits());
   }
   if(tpPrice - ask < minStopLevel)
   {
      tpPrice = NormalizeDouble(ask + minStopLevel, symInfo.Digits());
   }

   string comment = StringFormat("AT|Stoch=%.1f|RSI=%.1f", stochVal, rsiVal);

   if(trade.Buy(lots, _Symbol, ask, slPrice, tpPrice, comment))
   {
      Print("BUY opened: ", lots, " lots @ ", ask,
            " | SL=", slPrice, " | TP=", tpPrice,
            " | Stoch=", DoubleToString(stochVal, 2),
            " | RSI=", DoubleToString(rsiVal, 2));
   }
   else
   {
      Print("ERROR: Buy failed. Code=", trade.ResultRetcode(),
            " Desc=", trade.ResultRetcodeDescription());
   }
}

//+------------------------------------------------------------------+
//| Close position                                                    |
//+------------------------------------------------------------------+
void ClosePosition(string reason)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(posInfo.SelectByIndex(i))
      {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber)
         {
            double profit = posInfo.Profit();
            ulong  ticket = posInfo.Ticket();

            if(trade.PositionClose(ticket))
            {
               Print("Position closed. Ticket=", ticket,
                     " | Profit=", DoubleToString(profit, 2),
                     " | Reason: ", reason);
            }
            else
            {
               Print("ERROR: Close failed. Ticket=", ticket,
                     " Code=", trade.ResultRetcode());
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| Get current drawdown percentage                                   |
//+------------------------------------------------------------------+
double GetCurrentDrawdown()
{
   double equity  = accInfo.Equity();
   double balance = accInfo.Balance();

   // Use the higher of initial balance and current balance as peak
   double peak = MathMax(initialBalance, balance);
   if(peak == 0) return 0;

   return (peak - equity) / peak * 100.0;
}

//+------------------------------------------------------------------+
//| Check drawdown halt                                               |
//+------------------------------------------------------------------+
bool CheckDrawdownHalt()
{
   double dd = GetCurrentDrawdown();

   if(dd >= InpMaxDrawdownPct)
   {
      if(!drawdownHalt)
      {
         Print("!!! DRAWDOWN HALT !!! DD=", DoubleToString(dd, 2),
               "% >= Limit ", DoubleToString(InpMaxDrawdownPct, 2), "%");
         Print("Closing all positions and halting trading.");
         ClosePosition("Drawdown Halt");
         drawdownHalt = true;
      }
      return true;
   }

   // Reset halt if drawdown recovers below half the limit
   if(drawdownHalt && dd < InpMaxDrawdownPct / 2.0)
   {
      Print("Drawdown recovered to ", DoubleToString(dd, 2), "%. Resuming trading.");
      drawdownHalt = false;
   }

   return drawdownHalt;
}

//+------------------------------------------------------------------+
//| OnTrade - track position events                                   |
//+------------------------------------------------------------------+
void OnTrade()
{
   // Update peak balance for drawdown tracking
   double balance = accInfo.Balance();
   if(balance > initialBalance)
      initialBalance = balance;
}

//+------------------------------------------------------------------+
//| Tester function for optimization                                  |
//+------------------------------------------------------------------+
double OnTester()
{
   // Custom optimization criterion: Sharpe-like ratio
   double profit      = TesterStatistics(STAT_PROFIT);
   double dd          = TesterStatistics(STAT_EQUITY_DD_RELATIVE);
   double trades      = TesterStatistics(STAT_TRADES);
   double profitFactor = TesterStatistics(STAT_PROFIT_FACTOR);

   if(dd == 0 || trades < 10)
      return 0;

   // Composite score: profit factor * (profit / drawdown)
   return profitFactor * (profit / dd);
}
//+------------------------------------------------------------------+
