//+------------------------------------------------------------------+
//|                              AgentTeam_Auto_strat_e4c42302.mq5    |
//|                   Auto-generated by FX AgentTeam EA Generator    |
//|                   Strategy: strat_e4c42302 v2                     |
//+------------------------------------------------------------------+
#property copyright "FX AgentTeam"
#property version   "2.00"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\AccountInfo.mqh>
#include <Trade\SymbolInfo.mqh>

//+------------------------------------------------------------------+
//| Input Parameters                                                  |
//+------------------------------------------------------------------+
input group "=== Indicator Settings ==="
input int      Inp_stoch_16_window = 16;     // Stochastic window
input int      Inp_stoch_16_smooth_window = 4;     // Stochastic smooth_window
input int      Inp_rsi_15_window = 15;     // RSI window

input group "=== Signal Thresholds ==="
input double   InpEntry1Value = 20;  // Entry 1: stoch_16 threshold_below
input double   InpEntry2Value = 35;  // Entry 2: RSI_15 threshold_below
input double   InpExit1Value = 80;   // Exit 1: stoch_16 threshold_above

input group "=== Risk Management ==="
input double   InpStopLossPct     = 3.2;   // Stop Loss (%)
input double   InpTakeProfitPct   = 5.9;   // Take Profit (%)
input double   InpRiskPerTrade    = 8.0;   // Max Position (% of Balance)
input double   InpMaxDrawdownPct  = 16.0;  // Max Drawdown (%)
input double   InpFixedLot        = 0.0;      // Fixed Lot (0=auto)

input group "=== General ==="
input int      InpMagicNumber     = 82531970; // Magic Number
input int      InpMaxSlippage     = 30;       // Max Slippage (points)
input ENUM_TIMEFRAMES InpTimeframe = PERIOD_D1; // Timeframe
input bool     InpTradeOnlyOnNewBar = true;   // Trade only on new bar

//+------------------------------------------------------------------+
//| Global Variables                                                  |
//+------------------------------------------------------------------+
CTrade         trade;
CPositionInfo  posInfo;
CAccountInfo   accInfo;
CSymbolInfo    symInfo;

int            handle_stoch_16;
int            handle_rsi_15;
double         buf_stoch_16_main[];
double         buf_stoch_16_signal[];
double         buf_rsi_15[];

datetime       lastBarTime;
double         peakBalance;
bool           drawdownHalt;

//+------------------------------------------------------------------+
//| Expert initialization                                             |
//+------------------------------------------------------------------+
int OnInit()
{
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpMaxSlippage);
   trade.SetTypeFilling(ORDER_FILLING_FOK);
   trade.SetMarginMode();

   symInfo.Name(_Symbol);
   symInfo.Refresh();

   handle_stoch_16 = iStochastic(_Symbol, InpTimeframe, 16, 4, 3, MODE_SMA, STO_LOWHIGH);
   if(handle_stoch_16 == INVALID_HANDLE) { Print("ERROR: Stochastic handle failed"); return INIT_FAILED; }
   handle_rsi_15 = iRSI(_Symbol, InpTimeframe, 15, PRICE_CLOSE);
   if(handle_rsi_15 == INVALID_HANDLE) { Print("ERROR: RSI handle failed"); return INIT_FAILED; }

   ArraySetAsSeries(buf_stoch_16_main, true);
   ArraySetAsSeries(buf_stoch_16_signal, true);
   ArraySetAsSeries(buf_rsi_15, true);

   lastBarTime  = 0;
   peakBalance  = accInfo.Balance();
   drawdownHalt = false;

   Print("=== AgentTeam EA [strat_e4c42302] Initialized ===");
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization                                           |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   if(handle_stoch_16 != INVALID_HANDLE) IndicatorRelease(handle_stoch_16);
   if(handle_rsi_15 != INVALID_HANDLE) IndicatorRelease(handle_rsi_15);
}

//+------------------------------------------------------------------+
//| OnTick                                                            |
//+------------------------------------------------------------------+
void OnTick()
{
   if(InpTradeOnlyOnNewBar && !IsNewBar()) return;

   symInfo.Refresh();
   symInfo.RefreshRates();

   if(CheckDrawdownHalt()) return;
   if(!RefreshIndicators()) return;

   double val_stoch_16_main = buf_stoch_16_main[1];
   double val_stoch_16_signal = buf_stoch_16_signal[1];
   double val_rsi_15 = buf_rsi_15[1];

   Comment(StringFormat("AgentTeam EA | %s\nStochastic: %.2f\nRSI: %.2f", _Symbol, val_stoch_16_main, val_rsi_15));

   if(HasPosition())
   {
      if(val_stoch_16_main > InpExit1Value)
         ClosePosition("Signal Exit");
   }
   else
   {
      if(val_stoch_16_main < InpEntry1Value && val_rsi_15 < InpEntry2Value)
         OpenBuy();
   }
}

//+------------------------------------------------------------------+
//| Utility Functions                                                 |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime t = iTime(_Symbol, InpTimeframe, 0);
   if(t == lastBarTime) return false;
   lastBarTime = t;
   return true;
}

bool RefreshIndicators()
{
   if(CopyBuffer(handle_stoch_16, MAIN_LINE, 0, 3, buf_stoch_16_main) < 3) return false;
   if(CopyBuffer(handle_stoch_16, SIGNAL_LINE, 0, 3, buf_stoch_16_signal) < 3) return false;
   if(CopyBuffer(handle_rsi_15, 0, 0, 3, buf_rsi_15) < 3) return false;
   return true;
}

bool HasPosition()
{
   for(int i = PositionsTotal()-1; i >= 0; i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber)
            return true;
   return false;
}

double CalculateLotSize(double slPoints)
{
   if(InpFixedLot > 0) return NormalizeLot(InpFixedLot);
   double risk = accInfo.Balance() * InpRiskPerTrade / 100.0;
   double tv = symInfo.TickValue();
   double ts = symInfo.TickSize();
   if(tv == 0 || ts == 0 || slPoints == 0) return NormalizeLot(symInfo.LotsMin());
   return NormalizeLot(risk / (slPoints / ts * tv));
}

double NormalizeLot(double lots)
{
   lots = MathMax(symInfo.LotsMin(), lots);
   lots = MathMin(symInfo.LotsMax(), lots);
   lots = MathFloor(lots / symInfo.LotsStep()) * symInfo.LotsStep();
   return NormalizeDouble(lots, 2);
}

void OpenBuy()
{
   double ask = symInfo.Ask();
   if(ask == 0) return;
   double sl = NormalizeDouble(ask * (1.0 - InpStopLossPct/100.0), symInfo.Digits());
   double tp = NormalizeDouble(ask * (1.0 + InpTakeProfitPct/100.0), symInfo.Digits());
   double minStop = symInfo.StopsLevel() * symInfo.Point();
   if(ask - sl < minStop) sl = NormalizeDouble(ask - minStop, symInfo.Digits());
   if(tp - ask < minStop) tp = NormalizeDouble(ask + minStop, symInfo.Digits());
   double lots = CalculateLotSize(ask - sl);
   if(trade.Buy(lots, _Symbol, ask, sl, tp, "AgentTeam"))
      Print("BUY: ", lots, " @ ", ask, " SL=", sl, " TP=", tp);
   else
      Print("BUY FAILED: ", trade.ResultRetcode(), " ", trade.ResultRetcodeDescription());
}

void ClosePosition(string reason)
{
   for(int i = PositionsTotal()-1; i >= 0; i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber)
         {
            trade.PositionClose(posInfo.Ticket());
            Print("CLOSED: Profit=", posInfo.Profit(), " Reason=", reason);
         }
}

double GetDrawdown()
{
   double peak = MathMax(peakBalance, accInfo.Balance());
   if(peak == 0) return 0;
   return (peak - accInfo.Equity()) / peak * 100.0;
}

bool CheckDrawdownHalt()
{
   double dd = GetDrawdown();
   if(dd >= InpMaxDrawdownPct)
   {
      if(!drawdownHalt)
      {
         Print("!!! DRAWDOWN HALT !!! DD=", dd, "%");
         ClosePosition("Drawdown Halt");
         drawdownHalt = true;
      }
      return true;
   }
   if(drawdownHalt && dd < InpMaxDrawdownPct / 2.0)
   {
      drawdownHalt = false;
      Print("Drawdown recovered. Resuming.");
   }
   return drawdownHalt;
}

void OnTrade()
{
   double bal = accInfo.Balance();
   if(bal > peakBalance) peakBalance = bal;
}

double OnTester()
{
   double profit = TesterStatistics(STAT_PROFIT);
   double dd = TesterStatistics(STAT_EQUITY_DD_RELATIVE);
   double trades = TesterStatistics(STAT_TRADES);
   double pf = TesterStatistics(STAT_PROFIT_FACTOR);
   if(dd == 0 || trades < 10) return 0;
   return pf * (profit / dd);
}
//+------------------------------------------------------------------+
