"""Automatically generate MT5 EA (.mq5) from AgentTeam strategy JSON."""

from __future__ import annotations
import json
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from models.strategy import Strategy


# Maps AgentTeam indicator names to MT5 indicator creation code
INDICATOR_MAP = {
    "RSI": {
        "handle": 'iRSI(_Symbol, InpTimeframe, {window}, PRICE_CLOSE)',
        "buffers": 1,
        "var_prefix": "rsi",
    },
    "Stochastic": {
        "handle": 'iStochastic(_Symbol, InpTimeframe, {window}, {smooth_window}, 3, MODE_SMA, STO_LOWHIGH)',
        "buffers": 2,
        "var_prefix": "stoch",
    },
    "SMA": {
        "handle": 'iMA(_Symbol, InpTimeframe, {window}, 0, MODE_SMA, PRICE_CLOSE)',
        "buffers": 1,
        "var_prefix": "sma",
    },
    "EMA": {
        "handle": 'iMA(_Symbol, InpTimeframe, {window}, 0, MODE_EMA, PRICE_CLOSE)',
        "buffers": 1,
        "var_prefix": "ema",
    },
    "MACD": {
        "handle": 'iMACD(_Symbol, InpTimeframe, {window_fast}, {window_slow}, {window_sign}, PRICE_CLOSE)',
        "buffers": 2,
        "var_prefix": "macd",
    },
    "BollingerBands": {
        "handle": 'iBands(_Symbol, InpTimeframe, {window}, 0, {window_dev}, PRICE_CLOSE)',
        "buffers": 3,
        "var_prefix": "bb",
    },
    "ATR": {
        "handle": 'iATR(_Symbol, InpTimeframe, {window})',
        "buffers": 1,
        "var_prefix": "atr",
    },
}


def generate_ea(strategy: Strategy) -> str:
    """Generate complete MQL5 EA source code from a Strategy object."""

    # Collect indicator info
    indicators = []
    for i, ind in enumerate(strategy.indicators):
        info = INDICATOR_MAP.get(ind.name)
        if not info:
            raise ValueError(f"Unsupported indicator: {ind.name}")
        key_param = list(ind.params.values())[0]
        indicators.append({
            "name": ind.name,
            "params": ind.params,
            "handle_code": info["handle"].format(**ind.params),
            "buffers": info["buffers"],
            "prefix": f"{info['var_prefix']}_{key_param}",
            "var_prefix": info["var_prefix"],
            "index": i,
        })

    # Build input parameters section
    input_params = _build_input_params(strategy, indicators)

    # Build handle declarations
    handle_decls = _build_handle_declarations(indicators)

    # Build buffer declarations
    buffer_decls = _build_buffer_declarations(indicators)

    # Build handle creation in OnInit
    handle_inits = _build_handle_inits(indicators)

    # Build buffer setup
    buffer_setups = _build_buffer_setups(indicators)

    # Build indicator refresh
    refresh_code = _build_refresh_code(indicators)

    # Build value extraction
    value_extract = _build_value_extraction(indicators)

    # Build entry condition
    entry_cond = _build_condition(strategy.entry_rules, indicators, "&&")

    # Build exit condition
    exit_cond = _build_condition(strategy.exit_rules, indicators, "||")

    # Build comment display
    comment_display = _build_comment_display(indicators)

    ea_code = f'''//+------------------------------------------------------------------+
//|                              AgentTeam_Auto_{strategy.id}.mq5    |
//|                   Auto-generated by FX AgentTeam EA Generator    |
//|                   Strategy: {strategy.id} v{strategy.version}                     |
//+------------------------------------------------------------------+
#property copyright "FX AgentTeam"
#property version   "{strategy.version}.00"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\AccountInfo.mqh>
#include <Trade\\SymbolInfo.mqh>

//+------------------------------------------------------------------+
//| Input Parameters                                                  |
//+------------------------------------------------------------------+
{input_params}

input group "=== Risk Management ==="
input double   InpStopLossPct     = {strategy.risk.stop_loss_pct * 100:.1f};   // Stop Loss (%)
input double   InpTakeProfitPct   = {strategy.risk.take_profit_pct * 100:.1f};   // Take Profit (%)
input double   InpRiskPerTrade    = {strategy.risk.max_position_pct * 100:.1f};   // Max Position (% of Balance)
input double   InpMaxDrawdownPct  = {strategy.risk.max_drawdown_pct * 100:.1f};  // Max Drawdown (%)
input double   InpFixedLot        = 0.0;      // Fixed Lot (0=auto)

input group "=== General ==="
input int      InpMagicNumber     = {abs(hash(strategy.id)) % 99999999}; // Magic Number
input int      InpMaxSlippage     = 30;       // Max Slippage (points)
input ENUM_TIMEFRAMES InpTimeframe = PERIOD_D1; // Timeframe
input bool     InpTradeOnlyOnNewBar = true;   // Trade only on new bar

//+------------------------------------------------------------------+
//| Global Variables                                                  |
//+------------------------------------------------------------------+
CTrade         trade;
CPositionInfo  posInfo;
CAccountInfo   accInfo;
CSymbolInfo    symInfo;

{handle_decls}
{buffer_decls}

datetime       lastBarTime;
double         peakBalance;
bool           drawdownHalt;

//+------------------------------------------------------------------+
//| Expert initialization                                             |
//+------------------------------------------------------------------+
int OnInit()
{{
   trade.SetExpertMagicNumber(InpMagicNumber);
   trade.SetDeviationInPoints(InpMaxSlippage);
   trade.SetTypeFilling(ORDER_FILLING_FOK);
   trade.SetMarginMode();

   symInfo.Name(_Symbol);
   symInfo.Refresh();

{handle_inits}

{buffer_setups}

   lastBarTime  = 0;
   peakBalance  = accInfo.Balance();
   drawdownHalt = false;

   Print("=== AgentTeam EA [{strategy.id}] Initialized ===");
   return INIT_SUCCEEDED;
}}

//+------------------------------------------------------------------+
//| Expert deinitialization                                           |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
{_build_handle_releases(indicators)}
}}

//+------------------------------------------------------------------+
//| OnTick                                                            |
//+------------------------------------------------------------------+
void OnTick()
{{
   if(InpTradeOnlyOnNewBar && !IsNewBar()) return;

   symInfo.Refresh();
   symInfo.RefreshRates();

   if(CheckDrawdownHalt()) return;
   if(!RefreshIndicators()) return;

{value_extract}

{comment_display}

   if(HasPosition())
   {{
      if({exit_cond})
         ClosePosition("Signal Exit");
   }}
   else
   {{
      if({entry_cond})
         OpenBuy();
   }}
}}

//+------------------------------------------------------------------+
//| Utility Functions                                                 |
//+------------------------------------------------------------------+
bool IsNewBar()
{{
   datetime t = iTime(_Symbol, InpTimeframe, 0);
   if(t == lastBarTime) return false;
   lastBarTime = t;
   return true;
}}

bool RefreshIndicators()
{{
{refresh_code}
   return true;
}}

bool HasPosition()
{{
   for(int i = PositionsTotal()-1; i >= 0; i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber)
            return true;
   return false;
}}

double CalculateLotSize(double slPoints)
{{
   if(InpFixedLot > 0) return NormalizeLot(InpFixedLot);
   double risk = accInfo.Balance() * InpRiskPerTrade / 100.0;
   double tv = symInfo.TickValue();
   double ts = symInfo.TickSize();
   if(tv == 0 || ts == 0 || slPoints == 0) return NormalizeLot(symInfo.LotsMin());
   return NormalizeLot(risk / (slPoints / ts * tv));
}}

double NormalizeLot(double lots)
{{
   lots = MathMax(symInfo.LotsMin(), lots);
   lots = MathMin(symInfo.LotsMax(), lots);
   lots = MathFloor(lots / symInfo.LotsStep()) * symInfo.LotsStep();
   return NormalizeDouble(lots, 2);
}}

void OpenBuy()
{{
   double ask = symInfo.Ask();
   if(ask == 0) return;
   double sl = NormalizeDouble(ask * (1.0 - InpStopLossPct/100.0), symInfo.Digits());
   double tp = NormalizeDouble(ask * (1.0 + InpTakeProfitPct/100.0), symInfo.Digits());
   double minStop = symInfo.StopsLevel() * symInfo.Point();
   if(ask - sl < minStop) sl = NormalizeDouble(ask - minStop, symInfo.Digits());
   if(tp - ask < minStop) tp = NormalizeDouble(ask + minStop, symInfo.Digits());
   double lots = CalculateLotSize(ask - sl);
   if(trade.Buy(lots, _Symbol, ask, sl, tp, "AgentTeam"))
      Print("BUY: ", lots, " @ ", ask, " SL=", sl, " TP=", tp);
   else
      Print("BUY FAILED: ", trade.ResultRetcode(), " ", trade.ResultRetcodeDescription());
}}

void ClosePosition(string reason)
{{
   for(int i = PositionsTotal()-1; i >= 0; i--)
      if(posInfo.SelectByIndex(i))
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber)
         {{
            trade.PositionClose(posInfo.Ticket());
            Print("CLOSED: Profit=", posInfo.Profit(), " Reason=", reason);
         }}
}}

double GetDrawdown()
{{
   double peak = MathMax(peakBalance, accInfo.Balance());
   if(peak == 0) return 0;
   return (peak - accInfo.Equity()) / peak * 100.0;
}}

bool CheckDrawdownHalt()
{{
   double dd = GetDrawdown();
   if(dd >= InpMaxDrawdownPct)
   {{
      if(!drawdownHalt)
      {{
         Print("!!! DRAWDOWN HALT !!! DD=", dd, "%");
         ClosePosition("Drawdown Halt");
         drawdownHalt = true;
      }}
      return true;
   }}
   if(drawdownHalt && dd < InpMaxDrawdownPct / 2.0)
   {{
      drawdownHalt = false;
      Print("Drawdown recovered. Resuming.");
   }}
   return drawdownHalt;
}}

void OnTrade()
{{
   double bal = accInfo.Balance();
   if(bal > peakBalance) peakBalance = bal;
}}

double OnTester()
{{
   double profit = TesterStatistics(STAT_PROFIT);
   double dd = TesterStatistics(STAT_EQUITY_DD_RELATIVE);
   double trades = TesterStatistics(STAT_TRADES);
   double pf = TesterStatistics(STAT_PROFIT_FACTOR);
   if(dd == 0 || trades < 10) return 0;
   return pf * (profit / dd);
}}
//+------------------------------------------------------------------+
'''
    return ea_code


def _build_input_params(strategy, indicators):
    lines = ['input group "=== Indicator Settings ==="']
    for ind in indicators:
        for param, val in ind["params"].items():
            if isinstance(val, float):
                lines.append(f'input double   Inp_{ind["prefix"]}_{param} = {val};  // {ind["name"]} {param}')
            else:
                lines.append(f'input int      Inp_{ind["prefix"]}_{param} = {val};     // {ind["name"]} {param}')

    # Entry/exit thresholds
    lines.append('')
    lines.append('input group "=== Signal Thresholds ==="')
    for i, rule in enumerate(strategy.entry_rules):
        if "value" in rule.params:
            lines.append(f'input double   InpEntry{i+1}Value = {rule.params["value"]};  // Entry {i+1}: {rule.params.get("indicator", "")} {rule.type}')
    for i, rule in enumerate(strategy.exit_rules):
        if "value" in rule.params:
            lines.append(f'input double   InpExit{i+1}Value = {rule.params["value"]};   // Exit {i+1}: {rule.params.get("indicator", "")} {rule.type}')

    return "\n".join(lines)


def _build_handle_declarations(indicators):
    lines = []
    for ind in indicators:
        lines.append(f'int            handle_{ind["prefix"]};')
    return "\n".join(lines)


def _build_buffer_declarations(indicators):
    lines = []
    for ind in indicators:
        if ind["buffers"] == 1:
            lines.append(f'double         buf_{ind["prefix"]}[];')
        elif ind["buffers"] == 2:
            lines.append(f'double         buf_{ind["prefix"]}_main[];')
            lines.append(f'double         buf_{ind["prefix"]}_signal[];')
        elif ind["buffers"] == 3:
            lines.append(f'double         buf_{ind["prefix"]}_mid[];')
            lines.append(f'double         buf_{ind["prefix"]}_upper[];')
            lines.append(f'double         buf_{ind["prefix"]}_lower[];')
    return "\n".join(lines)


def _build_handle_inits(indicators):
    lines = []
    for ind in indicators:
        lines.append(f'   handle_{ind["prefix"]} = {ind["handle_code"]};')
        lines.append(f'   if(handle_{ind["prefix"]} == INVALID_HANDLE) {{ Print("ERROR: {ind["name"]} handle failed"); return INIT_FAILED; }}')
    return "\n".join(lines)


def _build_buffer_setups(indicators):
    lines = []
    for ind in indicators:
        if ind["buffers"] == 1:
            lines.append(f'   ArraySetAsSeries(buf_{ind["prefix"]}, true);')
        elif ind["buffers"] == 2:
            lines.append(f'   ArraySetAsSeries(buf_{ind["prefix"]}_main, true);')
            lines.append(f'   ArraySetAsSeries(buf_{ind["prefix"]}_signal, true);')
        elif ind["buffers"] == 3:
            lines.append(f'   ArraySetAsSeries(buf_{ind["prefix"]}_mid, true);')
            lines.append(f'   ArraySetAsSeries(buf_{ind["prefix"]}_upper, true);')
            lines.append(f'   ArraySetAsSeries(buf_{ind["prefix"]}_lower, true);')
    return "\n".join(lines)


def _build_refresh_code(indicators):
    lines = []
    for ind in indicators:
        h = f'handle_{ind["prefix"]}'
        if ind["buffers"] == 1:
            lines.append(f'   if(CopyBuffer({h}, 0, 0, 3, buf_{ind["prefix"]}) < 3) return false;')
        elif ind["buffers"] == 2:
            lines.append(f'   if(CopyBuffer({h}, MAIN_LINE, 0, 3, buf_{ind["prefix"]}_main) < 3) return false;')
            lines.append(f'   if(CopyBuffer({h}, SIGNAL_LINE, 0, 3, buf_{ind["prefix"]}_signal) < 3) return false;')
        elif ind["buffers"] == 3:
            lines.append(f'   if(CopyBuffer({h}, BASE_LINE, 0, 3, buf_{ind["prefix"]}_mid) < 3) return false;')
            lines.append(f'   if(CopyBuffer({h}, UPPER_BAND, 0, 3, buf_{ind["prefix"]}_upper) < 3) return false;')
            lines.append(f'   if(CopyBuffer({h}, LOWER_BAND, 0, 3, buf_{ind["prefix"]}_lower) < 3) return false;')
    return "\n".join(lines)


def _build_value_extraction(indicators):
    lines = []
    for ind in indicators:
        if ind["buffers"] == 1:
            lines.append(f'   double val_{ind["prefix"]} = buf_{ind["prefix"]}[1];')
        elif ind["buffers"] == 2:
            lines.append(f'   double val_{ind["prefix"]}_main = buf_{ind["prefix"]}_main[1];')
            lines.append(f'   double val_{ind["prefix"]}_signal = buf_{ind["prefix"]}_signal[1];')
        elif ind["buffers"] == 3:
            lines.append(f'   double val_{ind["prefix"]}_mid = buf_{ind["prefix"]}_mid[1];')
            lines.append(f'   double val_{ind["prefix"]}_upper = buf_{ind["prefix"]}_upper[1];')
            lines.append(f'   double val_{ind["prefix"]}_lower = buf_{ind["prefix"]}_lower[1];')
    return "\n".join(lines)


def _resolve_indicator_var(indicator_ref: str, indicators: list) -> str:
    """Map an AgentTeam indicator reference to the MQL5 variable name."""
    ref = indicator_ref.lower()

    if ref == "close":
        return "symInfo.Last()"

    for ind in indicators:
        prefix = ind["prefix"].lower()
        # Direct match: stoch_16 -> val_stoch_16_main or val_stoch_16
        if ref == prefix:
            if ind["buffers"] == 1:
                return f'val_{ind["prefix"]}'
            else:
                return f'val_{ind["prefix"]}_main'
        # Sub-buffer match: stoch_signal_16
        if ref == f'{ind["var_prefix"]}_signal_{list(ind["params"].values())[0]}'.lower():
            return f'val_{ind["prefix"]}_signal'
        # MACD diff
        if "macd_diff" in ref and ind["name"] == "MACD":
            return f'val_{ind["prefix"]}_signal'  # Use signal line as proxy
        # BB upper/lower
        if "bb_upper" in ref and ind["name"] == "BollingerBands":
            return f'val_{ind["prefix"]}_upper'
        if "bb_lower" in ref and ind["name"] == "BollingerBands":
            return f'val_{ind["prefix"]}_lower'
        # Case-insensitive name match: RSI_15 -> val_rsi_15
        if ref == f'{ind["name"].lower()}_{list(ind["params"].values())[0]}'.lower():
            if ind["buffers"] == 1:
                return f'val_{ind["prefix"]}'
            else:
                return f'val_{ind["prefix"]}_main'

    return f'/* UNRESOLVED: {indicator_ref} */ 0'


def _build_condition(rules, indicators, combiner):
    parts = []
    for i, rule in enumerate(rules):
        p = rule.params
        val_ref = f"InpEntry{i+1}Value" if combiner == "&&" else f"InpExit{i+1}Value"

        if rule.type == "threshold_below":
            var = _resolve_indicator_var(p.get("indicator", ""), indicators)
            parts.append(f'{var} < {val_ref}')
        elif rule.type == "threshold_above":
            var = _resolve_indicator_var(p.get("indicator", ""), indicators)
            parts.append(f'{var} > {val_ref}')
        elif rule.type == "cross_above":
            fast = _resolve_indicator_var(p.get("fast", ""), indicators)
            slow = _resolve_indicator_var(p.get("slow", ""), indicators)
            parts.append(f'{fast} > {slow}')
        elif rule.type == "cross_below":
            fast = _resolve_indicator_var(p.get("fast", ""), indicators)
            slow = _resolve_indicator_var(p.get("slow", ""), indicators)
            parts.append(f'{fast} < {slow}')
        elif rule.type == "band_breakout":
            upper = _resolve_indicator_var(p.get("upper_band", ""), indicators)
            parts.append(f'symInfo.Last() > {upper}')
        elif rule.type == "band_breakdown":
            lower = _resolve_indicator_var(p.get("lower_band", ""), indicators)
            parts.append(f'symInfo.Last() < {lower}')

    if not parts:
        return "false"
    return f" {combiner} ".join(parts)


def _build_comment_display(indicators):
    fmt_parts = []
    val_parts = []
    for ind in indicators:
        if ind["buffers"] == 1:
            fmt_parts.append(f'{ind["name"]}: %.2f')
            val_parts.append(f'val_{ind["prefix"]}')
        else:
            fmt_parts.append(f'{ind["name"]}: %.2f')
            val_parts.append(f'val_{ind["prefix"]}_main')

    fmt_str = "AgentTeam EA | %s\\n" + "\\n".join(fmt_parts)
    val_str = ", _Symbol, " + ", ".join(val_parts)
    return f'   Comment(StringFormat("{fmt_str}"{val_str}));'


def _build_handle_releases(indicators):
    lines = []
    for ind in indicators:
        lines.append(f'   if(handle_{ind["prefix"]} != INVALID_HANDLE) IndicatorRelease(handle_{ind["prefix"]});')
    return "\n".join(lines)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Generate MT5 EA from AgentTeam strategy")
    parser.add_argument("--strategy", default="../output/strategies/best_strategy.json", help="Strategy JSON file")
    parser.add_argument("--output", default=None, help="Output .mq5 file")
    args = parser.parse_args()

    with open(args.strategy) as f:
        strategy = Strategy.from_json(f.read())

    code = generate_ea(strategy)

    output_path = args.output or f"AgentTeam_Auto_{strategy.id}.mq5"
    with open(output_path, "w") as f:
        f.write(code)

    print(f"EA generated: {output_path}")
    print(f"Strategy: {strategy.id} v{strategy.version}")
    print(f"Indicators: {', '.join(i.name for i in strategy.indicators)}")
    print(f"Copy to: MT5_Data_Folder/MQL5/Experts/")


if __name__ == "__main__":
    main()
